### PR TITLE
Add realtime private events

### LINKED ISSUE #37: Private event

### LINKED ISSUE #169: disconnected / reconnecting callbacks

### PR DESCRIPTION
**Pull request by yemartin**
Thank you for a very clean code @unhappychoice,  it made it very easy to contribute!

Resolves #37
Resolves #169

TODOs:

- [x] Add private events
- [x] Update README
- [x] Improve reconnect behavior
- [x] Provide ready / disconnected callbacks (*)
- [x] Code review by @unhappychoice 

 *: If users are going to rely on the private events to track order executions, they need to know when the socket was disconnected and reconnected, so they get the executions they have missed using the HTTP client.

### CODE REVIEW

**Comment by unhappychoice** [comment]
Thanks for the PR and caring even the readme file. 👋 

I'll merge this and release in next 1.1.0 version 💪 

BTW,  TODOs in the description is now #169

**Comment by unhappychoice** [comment]
Ah as you said in #166, this is WIP, isn't it?
Then I'll wait for it's going to be finished :smile:

**Comment by yemartin** [comment]
Yes, it still WIP 😅
I am planning to finish it next weekend.

**Comment by yemartin** [comment]
Hi @unhappychoice,

OK I think I am happy with the code now, but can you please review the changes? I tried to keep the commits self-contained to facilitate your review. Please don't hesitate to critique or ask for changes or improvements.

**Comment by yemartin** [comment]
PS: I don't have permission to set reviewers, so I added a "code review" item to the TODOs instead.

**Review by unhappychoice — APPROVED** [review]
image

**Comment by unhappychoice** [comment]
released in v1.2.0

**Comment by yemartin** [comment]
Thank you for the review and merge! 👍

**Pull request merged**
