### PR TITLE
:sparkles: Add pagination to public execution history

### PR DESCRIPTION
**Pull request by yemartin**
Add pagination parameters to the public execution history, as per the API documentation on the [Execution History](https://lightning.bitflyer.com/docs?lang=en#execution-history) endpoint.

### CODE REVIEW

**Comment by unhappychoice** [comment]
Sorry for being late :pray:

It seems totally good and thank you for the PR 😄

**Comment by yemartin** [comment]
Thank you for the merge! ☺️
I will rebase #167 on `master` then. Hopefully I get the chance to finish it this weekend.

**Comment by unhappychoice** [comment]
@all-contributors please add @yemartin for code

**Comment by unhappychoice** [comment]
@all-contributors please add @yemartin for code

**Comment by unhappychoice** [comment]
This is released in v1.1.0

**Pull request merged**
